---
driver_plugin: vagrant

driver_config:
  customize:
    memory: 2048
  network:
    - ["private_network", {ip: "192.168.33.33"}]

platforms:
  - name: centos-6.5
    driver_config:
      box: centos-6.5
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box

suites:
  - name: default
    run_list:
